-- MySQL Script generated by MySQL Workbench
-- Tue May  9 16:46:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pomiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pomiar` (
  `idPomiar` INT NOT NULL,
  `Wartosc` INT NULL,
  `Czas` VARCHAR(30) NULL,
  `Servo_idServo` INT NOT NULL,
  PRIMARY KEY (`idPomiar`),
  INDEX `fk_Pomiar_Servo_idx` (`Servo_idServo` ASC),
  CONSTRAINT `fk_Pomiar_Servo`
    FOREIGN KEY (`Servo_idServo`)
    REFERENCES `mydb`.`Servo` (`idServo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servo` (
  `idServo` INT NOT NULL,
  `Nazwa` VARCHAR(30) NULL,
  PRIMARY KEY (`idServo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pomiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pomiar` (
  `idPomiar` INT NOT NULL,
  `Wartosc` INT NULL,
  `Czas` VARCHAR(30) NULL,
  `Servo_idServo` INT NOT NULL,
  PRIMARY KEY (`idPomiar`),
  INDEX `fk_Pomiar_Servo_idx` (`Servo_idServo` ASC),
  CONSTRAINT `fk_Pomiar_Servo`
    FOREIGN KEY (`Servo_idServo`)
    REFERENCES `mydb`.`Servo` (`idServo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
